#!/usr/bin/env python3
"""Create a static standing reference motion from one retargeted CSV frame."""

from __future__ import annotations

import argparse
import csv
import json
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np


def _load_urdf_joint_names(urdf_path: Path) -> list[str]:
    root = ET.parse(urdf_path).getroot()
    return [
        joint.attrib["name"]
        for joint in root.findall("joint")
        if joint.attrib.get("type") != "fixed"
    ]


def _read_csv_rows(csv_path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with csv_path.open(newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        header = list(reader.fieldnames or [])
        rows = list(reader)
    if not rows:
        raise ValueError(f"No data rows in {csv_path}")
    return header, rows


def _float(row: dict[str, str], name: str) -> float:
    if name not in row:
        raise ValueError(f"CSV is missing required column: {name}")
    return float(row[name])


def create_static_motion(
    csv_path: Path,
    urdf_path: Path,
    output_path: Path,
    metadata_path: Path,
    frame: int,
    height_offset: float,
    duration: float,
    joint_unit: str,
) -> dict[str, object]:
    header, rows = _read_csv_rows(csv_path)
    if frame < 0 or frame >= len(rows):
        raise ValueError(f"frame={frame} is outside CSV frame range [0, {len(rows) - 1}]")
    if duration <= 0.0:
        raise ValueError("duration must be positive")

    row = rows[frame]
    joint_names = _load_urdf_joint_names(urdf_path)
    missing = [name for name in joint_names if name not in header]
    if missing:
        raise ValueError(f"CSV is missing joint columns required by URDF: {missing}")

    root_pos = np.array(
        [
            _float(row, "root_pos_x"),
            _float(row, "root_pos_y"),
            _float(row, "root_pos_z") + height_offset,
        ],
        dtype=np.float32,
    )
    # MotionLoader expects Isaac-style xyzw quaternions. The CSV stores wxyz.
    root_quat = np.array(
        [
            _float(row, "root_quat_x"),
            _float(row, "root_quat_y"),
            _float(row, "root_quat_z"),
            _float(row, "root_quat_w"),
        ],
        dtype=np.float64,
    )
    root_quat /= np.linalg.norm(root_quat)
    root_quat = root_quat.astype(np.float32)
    if joint_unit not in ("radians", "degrees"):
        raise ValueError("joint_unit must be either 'radians' or 'degrees'")
    joint_scale = np.pi / 180.0 if joint_unit == "degrees" else 1.0
    dof_pos = np.array([_float(row, name) * joint_scale for name in joint_names], dtype=np.float32)

    timestamps = np.array([0.0, duration], dtype=np.float32)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output_path,
        timestamps=timestamps,
        root_pos=np.stack([root_pos, root_pos]).astype(np.float32),
        root_quat=np.stack([root_quat, root_quat]).astype(np.float32),
        root_lin_vel=np.zeros((2, 3), dtype=np.float32),
        root_ang_vel=np.zeros((2, 3), dtype=np.float32),
        dof_pos=np.stack([dof_pos, dof_pos]).astype(np.float32),
        dof_vel=np.zeros((2, len(joint_names)), dtype=np.float32),
        joint_names=np.asarray(joint_names),
        fps=np.array(1.0 / duration, dtype=np.float32),
        dt=np.array(duration, dtype=np.float32),
        duration=np.array(duration, dtype=np.float32),
        source_csv=np.array(str(csv_path.as_posix())),
        source_frame=np.array(frame, dtype=np.int32),
        robot_urdf=np.array(str(urdf_path.as_posix())),
        root_height_offset=np.array(height_offset, dtype=np.float32),
    )

    metadata = {
        "source_csv": str(csv_path.as_posix()),
        "source_frame": frame,
        "processed_npz": str(output_path.as_posix()),
        "robot_urdf": str(urdf_path.as_posix()),
        "frame_count": 2,
        "joint_count": len(joint_names),
        "duration": duration,
        "dt": duration,
        "fps": 1.0 / duration,
        "root_height_offset": height_offset,
        "joint_unit": joint_unit,
        "joint_scale_to_radians": joint_scale,
        "root_pos": root_pos.tolist(),
        "root_quat_xyzw": root_quat.tolist(),
        "joint_names": joint_names,
        "notes": [
            "Static standing reference generated by repeating one CSV frame twice.",
            "Root/body velocities and DOF velocities are set to zero.",
            "CSV quaternion order is wxyz; generated NPZ quaternion order is xyzw.",
            "Joint positions are stored in radians in the generated NPZ.",
        ],
    }
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    return metadata


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", required=True, type=Path)
    parser.add_argument("--urdf", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--metadata", required=True, type=Path)
    parser.add_argument("--frame", type=int, default=0)
    parser.add_argument(
        "--height-offset",
        type=float,
        default=0.014,
        help="Meters to add to the CSV root height. Default clears the observed first-frame penetration.",
    )
    parser.add_argument("--duration", type=float, default=0.02)
    parser.add_argument(
        "--joint-unit",
        choices=("radians", "degrees"),
        default="radians",
        help="Unit of CSV joint position columns. Generated NPZ always stores radians.",
    )
    args = parser.parse_args()

    metadata = create_static_motion(
        args.csv,
        args.urdf,
        args.output,
        args.metadata,
        args.frame,
        args.height_offset,
        args.duration,
        args.joint_unit,
    )
    print(
        "wrote "
        f"{metadata['processed_npz']} from frame={metadata['source_frame']} "
        f"height_offset={metadata['root_height_offset']:.6f}"
    )


if __name__ == "__main__":
    main()
